### PR TITLE
Fixes TypeError: Cannot access offset of type string on string

### LINKED ISSUE #546: On Product Add Credit Form, TypeError is occured on submit
## Description
Drupal\apigee_m10n_add_credit\Plugin\AddCreditEntityType\Developer->getEntities() throws TypeError

## Steps to Reproduce
1. Go to 'Commerce > Product > USD(or any product)'
2. Click on 'Checkout'

## Actual Behavior
TypeError: : Cannot access offset of type string on string

## Expected Behavior
USD added to your cart. & Order Information & summary page should be seen without any error.

## Version Info
Drupal 10 & 11

### PR DESCRIPTION
**Pull request by kedarkhaire**
Fixes #546

### CODE REVIEW

File: modules/apigee_m10n_add_credit/src/Form/AddCreditAddToCartForm.php [hunk 1]
```diff
@@ -114,6 +115,7 @@ public function buildForm(array $form, FormStateInterface $form_state) {
         "{$default_value['target_type']}:{$default_value['target_id']}",
       ];
     }
+    }
```
Comment (divya-intelli) [inline modules/apigee_m10n_add_credit/src/Form/AddCreditAddToCartForm.php]: Looks like extra closing bracket.

Comment (kedarkhaire) [reply modules/apigee_m10n_add_credit/src/Form/AddCreditAddToCartForm.php]: updated

**Review by shishir-intelli — APPROVED** [review]
LGTM
